name = "ssh-keys"
main = "src/worker.ts"
compatibility_date = "2026-03-27"
routes = [{ pattern = "ssh-keys.kye.dev/*", zone_name = "kye.dev" }]
preview_urls = false

[build]
command = "node scripts/build-keys.js"
